cmake -DASSIMP_BUILD_TESTS=OFF^
	  -DASSIMP_BUILD_ASSIMP_TOOLS=OFF^
	  -DBUILD_BULLET2_DEMOS=OFF^
	  -DBUILD_BULLET_ROBOTICS_EXTRA=OFF^
	  -DBUILD_BULLET_ROBOTICS_GUI_EXTRA=OFF^
	  -DBUILD_CPU_DEMOS=OFF^
	  -DBUILD_OPENGL3_DEMOS=OFF^
	  -DBUILD_TESTING=OFF^
	  -DBUILD_UNIT_TESTS=OFF^
	  -DYAML_CPP_BUILD_TOOLS=OFF^
	  -DUSE_GLUT=OFF ..
cmake --build . --config %*
cd Exe\%*\
start AdHoc.exe
